In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')
submission = pd.read_csv('./sample_submission.csv')

In [3]:
train.head()

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,target
0,1,Female,disloyal Customer,22,Business travel,Eco,1599,3,0,3,...,4,5,4,4,4,5,4,0,0.0,0
1,2,Female,Loyal Customer,37,Business travel,Business,2810,2,4,4,...,5,5,4,2,1,5,2,18,18.0,0
2,3,Male,Loyal Customer,46,Business travel,Business,2622,1,1,1,...,4,4,4,4,5,4,3,0,0.0,1
3,4,Female,disloyal Customer,24,Business travel,Eco,2348,3,3,3,...,3,2,4,5,3,4,3,10,2.0,0
4,5,Female,Loyal Customer,58,Business travel,Business,105,3,3,3,...,4,4,4,4,4,4,5,0,0.0,1

In [4]:
pd.get_dummies()

   id  target
0   1       0
1   2       0
2   3       0
3   4       0
4   5       0

In [31]:
obj_arr = np.array(train.dtypes[pd.DataFrame(train.dtypes)[0]== 'object'].index)

array(['Gender', 'Customer Type', 'Type of Travel', 'Class'], dtype=object)

In [41]:
train_dummy = pd.get_dummies(train, columns = obj_arr)

In [46]:
train_corr = train_dummy[['Age', 'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink', 'Gate location',
       'Inflight wifi service', 'Inflight entertainment', 'Online support',
       'Ease of Online booking', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'target',
       'Gender_Female', 'Gender_Male', 'Customer Type_Loyal Customer',
       'Customer Type_disloyal Customer', 'Type of Travel_Business travel',
       'Type of Travel_Personal Travel', 'Class_Business', 'Class_Eco',
       'Class_Eco Plus']].corr().reset_index()

In [47]:
train_corr

,index,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,...,target,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus
0,Age,1.000000,-0.244648,0.007376,0.034815,0.010523,-0.001826,0.023508,0.113550,0.119829,...,0.107226,0.003482,-0.003482,0.268995,-0.268995,0.052900,-0.052900,0.122359,-0.136621,0.025555
1,Flight Distance,-0.244648,1.000000,-0.022531,0.007639,0.025861,0.017033,-0.009141,-0.038677,-0.049503,...,-0.052059,-0.123408,0.123408,-0.040098,0.040098,0.119303,-0.119303,0.159560,-0.122854,-0.070198
2,Seat comfort,0.007376,-0.022531,1.000000,0.440134,0.726269,0.415367,0.149537,0.425375,0.125299,...,0.271270,0.075869,-0.075869,0.040791,-0.040791,0.006467,-0.006467,-0.026803,0.022466,0.008367
3,Departure/Arrival time convenient,0.034815,0.007639,0.440134,1.000000,0.517608,0.524651,0.008539,0.109779,0.017806,...,-0.010653,-0.033121,0.033121,0.225245,-0.225245,-0.190636,0.190636,-0.042984,0.032698,0.019654
4,Food and drink,0.010523,0.025861,0.726269,0.517608,1.000000,0.518372,0.031152,0.369300,0.034901,...,0.145126,0.072313,-0.072313,0.050667,-0.050667,0.051107,-0.051107,0.048585,-0.040757,-0.015105
5,Gate location,-0.001826,0.017033,0.415367,0.524651,0.518372,1.000000,0.012270,0.025202,0.030801,...,0.003213,0.017012,-0.017012,0.005149,-0.005149,0.028135,-0.028135,0.020672,-0.019315,-0.002731
6,Inflight wifi service,0.023508,-0.009141,0.149537,0.008539,0.031152,0.012270,1.000000,0.274032,0.563290,...,0.242427,0.037314,-0.037314,0.064159,-0.064159,0.021098,-0.021098,0.072480,-0.057899,-0.027968
7,Inflight entertainment,0.113550,-0.038677,0.425375,0.109779,0.369300,0.025202,0.274032,1.000000,0.424481,...,0.522935,0.144514,-0.144514,0.219638,-0.219638,0.102683,-0.102683,0.245570,-0.219680,-0.050752
8,Online support,0.119829,-0.049503,0.125299,0.017806,0.034901,0.030801,0.563290,0.424481,1.000000,...,0.411944,0.124389,-0.124389,0.171225,-0.171225,0.046100,-0.046100,0.176613,-0.158739,-0.035104
9,Ease of Online booking,0.080516,-0.031702,0.232216,0.026262,0.084424,0.027807,0.602040,0.333921,0.620806,...,0.447784,0.117756,-0.117756,0.128285,-0.128285,0.040286,-0.040286,0.119014,-0.099646,-0.037364
10,On-board service,0.043528,-0.029641,0.125858,0.074988,0.078108,0.008458,0.074805,0.182189,0.166119,...,0.359699,0.111435,-0.111435,0.064931,-0.064931,-0.022546,0.022546,0.164486,-0.111051,-0.101558
11,Leg room service,0.090474,-0.008762,0.155483,0.007449,0.093921,-0.021740,0.047759,0.161948,0.157694,...,0.311086,0.098130,-0.098130,0.078689,-0.078689,0.021225,-0.021225,0.149815,-0.115286,-0.066032
12,Baggage handling,-0.017721,0.039258,0.111575,0.060434,0.041716,-0.002328,0.041580,0.102035,0.079366,...,0.232302,0.039548,-0.039548,-0.020478,0.020478,-0.016129,0.016129,0.129584,-0.093115,-0.069474
13,Checkin service,0.039041,-0.010615,0.032431,0.044871,0.011384,-0.040837,0.087516,0.211560,0.212608,...,0.248975,0.029540,-0.029540,0.026835,-0.026835,-0.054509,0.054509,0.160427,-0.113389,-0.089545
14,Cleanliness,-0.022679,0.017461,0.104477,0.066656,0.053679,-0.005195,0.027640,0.075492,0.075789,...,0.234848,0.031257,-0.031257,-0.015002,0.015002,-0.046899,0.046899,0.105767,-0.077503,-0.053894
15,Online boarding,0.042943,-0.010123,0.152038,0.028601,0.050461,0.039442,0.632049,0.353772,0.675139,...,0.351370,0.077914,-0.077914,0.087781,-0.087781,0.021312,-0.021312,0.103161,-0.082113,-0.040363
16,Departure Delay in Minutes,-0.017425,0.107033,-0.025094,0.036465,-0.012885,0.000162,-0.041744,-0.047464,-0.052909,...,-0.104975,-0.017899,0.017899,-0.018606,0.018606,-0.000450,0.000450,-0.020424,0.024964,-0.008307
17,Arrival Delay in Minutes,-0.017370,0.105158,-0.021749,0.039235,-0.006892,0.009884,-0.044477,-0.050991,-0.055446,...,-0.112338,-0.017777,0.017777,-0.020224,0.020224,0.007270,-0.007270,-0.025472,0.029251,-0.006837
18,target,0.107226,-0.052059,0.271270,-0.010653,0.145126,0.003213,0.242427,0.522935,0.411944,...,1.000000,0.233619,-0.233619,0.271471,-0.271471,0.133565,-0.133565,0.300441,-0.266407,-0.066510
19,Gender_Female,0.003482,-0.123408,0.075869,-0.033121,0.072313,0.017012,0.037314,0.144514,0.124389,...,0.233619,1.000000,-1.000000,-0.020998,0.020998,0.015590,-0.015590,-0.001393,-0.019594,0.039299
20,Gender_Male,-0.003482,0.123408,-0.075869,0.033121,-0.072313,-0.017012,-0.037314,-0.144514,-0.124389,...,-0.233619,-1.000000,1.000000,0.020998,-0.020998,-0.015590,0.015590,0.001393,0.019594,-0.039299
21,Customer Type_Loyal Customer,0.268995,-0.040098,0.040791,0.225245,0.050667,0.005149,0.064159,0.219638,0.171225,...,0.271471,-0.020998,0.020998,1.000000,-1.000000,-0.303921,0.303921,0.066137,-0.102158,0.066808
22,Customer Type_disloyal Customer,-0.268995,0.040098,-0.040791,-0.225245,-0.050667,-0.005149,-0.064159,-0.219638,-0.171225,...,-0.271471,0.020998,-0.020998,-1.000000,1.000000,0.303921,-0.303921,-0.066137,0.102158,-0.066808
23,Type of Travel_Business travel,0.052900,0.119303,0.006467,-0.190636,0.051107,0.028135,0.021098,0.102683,0.046100,...,0.133565,0.015590,-0.015590,-0.303921,0.303921,1.000000,-1.000000,0.562338,-0.513610,-0.096457
24,Type of Travel_Personal Travel,-0.052900,-0.119303,-0.006467,0.190636,-0.051107,-0.028135,-0.021098,-0.102683,-0.046100,...,-0.133565,-0.015590,0.015590,0.303921,-0.303921,-1.000000,1.000000,-0.562338,0.513610,0.096457
25,Class_Business,0.122359,0.159560,-0.026803,-0.042984,0.048585,0.020672,0.072480,0.245570,0.176613,...,0.300441,-0.001393,0.001393,0.066137,-0.066137,0.562338,-0.562338,1.000000,-0.858022,-0.275092
26,Class_Eco,-0.136621,-0.122854,0.022466,0.032698,-0.040757,-0.019315,-0.057899,-0.219680,-0.158739,...,-0.266407,-0.019594,0.019594,-0.102158,0.102158,-0.513610,0.513610,-0.858022,1.000000,-0.257762
27,Class_Eco Plus,0.025555,-0.070198,0.008367,0.019654,-0.015105,-0.002731,-0.027968,-0.050752,-0.035104,...,-0.066510,0.039299,-0.039299,0.066808,-0.066808,-0.096457,0.096457,-0.275092,-0.257762,1.000000

In [51]:
train_corr = train_corr.rename(columns={'index':'columns'})

In [60]:
train_corr[train_corr['columns']=='target']

,columns,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,...,target,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus
18,target,0.107226,-0.052059,0.27127,-0.010653,0.145126,0.003213,0.242427,0.522935,0.411944,...,1.0,0.233619,-0.233619,0.271471,-0.271471,0.133565,-0.133565,0.300441,-0.266407,-0.06651

In [5]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [6]:
X_train = pd.DataFrame(train['Arrival Delay in Minutes'])
y_train =train['target']

In [7]:
X_test = pd.DataFrame(test['Arrival Delay in Minutes'])

In [8]:
model = lr.fit(X_train, y_train)

In [9]:
y_pred = model.predict(X_test)

In [11]:
submission['target'] = y_pred

In [15]:
submission.to_csv("submission.csv",index=False)

In [16]:
import numpy as np

def ACCURACY(true, pred):   
    score = np.mean(true==pred)
    return score

In [17]:
submission

        id  target
0        1       0
1        2       1
2        3       1
3        4       1
4        5       1
...    ...     ...
1995  1996       1
1996  1997       0
1997  1998       1
1998  1999       0
1999  2000       1

[2000 rows x 2 columns]

In [10]:
submission

        id  target
0        1       0
1        2       0
2        3       0
3        4       0
4        5       0
...    ...     ...
1995  1996       0
1996  1997       0
1997  1998       0
1998  1999       0
1999  2000       0

[2000 rows x 2 columns]